language: c
sudo: false
os:
  - linux
  - osx
env:
  matrix:
    - CONFIGURE_ARGS=--with-pydebug
    - CONFIGURE_ARGS=""
script: "./configure $CONFIGURE_ARGS && make -j2 && make test TESTOPTS='-w -j3'"
